import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "swiper/css";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { auth } from "@/auth";
import QueryProviders from "@/providers/QueryClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased px-8 space-y-4",
          inter.className
        )}
      >
        <QueryProviders>
          <Navbar session={session} />
          {children}
        </QueryProviders>
      </body>
    </html>
  );
}
